# Generated by Django 3.2.12 on 2022-02-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_period_accessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geographic_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('elevation', models.CharField(max_length=100)),
                ('evolution_of_cave', models.CharField(max_length=100)),
                ('land_status', models.CharField(max_length=100)),
                ('accessibility', models.TextField()),
                ('others', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
