# Generated by Django 3.2.12 on 2022-02-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0005_excisting_land_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='demographic_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brgy', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.CharField(blank=True, max_length=50, null=True)),
                ('households', models.CharField(blank=True, max_length=50, null=True)),
                ('families', models.CharField(blank=True, max_length=50, null=True)),
                ('livelihood', models.CharField(blank=True, max_length=80, null=True)),
                ('others', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
