# Generated by Django 3.2.12 on 2022-02-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0006_demographic_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='uses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_activity', models.CharField(blank=True, max_length=100, null=True)),
                ('implementation_period', models.CharField(blank=True, max_length=100, null=True)),
                ('station_covered', models.CharField(blank=True, max_length=50, null=True)),
                ('implementing_agencies', models.CharField(blank=True, max_length=155, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
