# Generated by Django 3.2.12 on 2022-02-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0007_uses'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=200)),
                ('region_id', models.CharField(max_length=5)),
                ('province_id', models.CharField(max_length=10)),
                ('city_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Layers_attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=80, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('total_of_cave', models.IntegerField(blank=True, null=True)),
                ('type_of_animal', models.CharField(blank=True, max_length=100, null=True)),
                ('total_of_male', models.IntegerField(blank=True, null=True)),
                ('total_of_female', models.IntegerField(blank=True, null=True)),
                ('overall_gender', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Meduim'), ('S', 'Small'), ('NS', 'Not Specified')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='caveinventory',
            name='city',
            field=models.CharField(choices=[('012801', 'Adams'), ('012802', 'Bacarra'), ('012803', 'Badoc'), ('012804', 'Bangui'), ('012805', 'City of Batac'), ('012806', 'Burgos'), ('012807', 'Carasi'), ('012808', 'Currimao'), ('012809', 'Dingras'), ('012810', 'Dumalneg'), ('012811', 'Banna'), ('012812', 'City of Laoag (Capital)'), ('012813', 'Marcos'), ('012814', 'Nueva Era'), ('012815', 'Pagudpud'), ('012816', 'Paoay'), ('012817', 'Pasuquin'), ('012818', 'Piddig'), ('012819', 'Pinili'), ('012820', 'San Nicolas'), ('012821', 'Sarrat')], max_length=150),
        ),
        migrations.AlterField(
            model_name='caveinventory',
            name='region',
            field=models.CharField(choices=[('Region I', 'Ilocos Region'), ('Region II', 'Cagayan Valley'), ('Region III', 'Central Luzon'), ('Region IV', 'Calabarzon'), ('Region', 'Mimaropa'), ('Region V', 'Bicol Region'), ('Region VI', 'Western Visayas'), ('Region VII', 'Central Visayas'), ('Region VIII', 'Eastern Visayas'), ('Region IX', 'Zamboanga Peninsula'), ('Region X', 'Northern Mindanao'), ('Region XI', 'Davao Region'), ('Region XII', 'SOCCSKSARGEN'), ('Region XIII', 'Caraga'), ('NCR', 'National Capital Region'), ('CAR', 'Cordillera Administrative Region'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao'), ('NS', 'Zamboanga Peninsula')], max_length=150),
        ),
    ]
