# Generated by Django 3.2.12 on 2022-03-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0009_auto_20220302_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='caveinventory',
            name='region',
            field=models.CharField(choices=[('Ilocos', 'Ilocos'), ('Cagayan Valley', 'Cagayan Valley'), ('Central Luzon', 'Central Luzon'), ('Calabarzon', 'Calabarzon'), ('Mimaropa', 'Mimaropa'), ('Bicol Region', 'Bicol Region'), ('Western Visayas', 'Western Visayas'), ('Central Visayas', 'Central Visayas'), ('Eastern Visayas', 'Eastern Visayas'), ('Zamboanga Peninsula', 'Zamboanga Peninsula'), ('Northern Mindanao', 'Northern Mindanao'), ('Davao', 'Davao'), ('SOCCSKSARGEN', 'SOCCSKSARGEN'), ('Caraga', 'Caraga'), ('National Capital Region', 'National Capital Region'), ('Cordillera Administrative Region', 'Cordillera Administrative Region'), ('Bangsamoro Autonomous Region in Muslim Mindanao', 'Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=150),
        ),
        migrations.AlterField(
            model_name='layers_attribute',
            name='region',
            field=models.CharField(blank=True, choices=[('Ilocos', 'Ilocos'), ('Cagayan Valley', 'Cagayan Valley'), ('Central Luzon', 'Central Luzon'), ('Calabarzon', 'Calabarzon'), ('Mimaropa', 'Mimaropa'), ('Bicol Region', 'Bicol Region'), ('Western Visayas', 'Western Visayas'), ('Central Visayas', 'Central Visayas'), ('Eastern Visayas', 'Eastern Visayas'), ('Zamboanga Peninsula', 'Zamboanga Peninsula'), ('Northern Mindanao', 'Northern Mindanao'), ('Davao', 'Davao'), ('SOCCSKSARGEN', 'SOCCSKSARGEN'), ('Caraga', 'Caraga'), ('National Capital Region', 'National Capital Region'), ('Cordillera Administrative Region', 'Cordillera Administrative Region'), ('Bangsamoro Autonomous Region in Muslim Mindanao', 'Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='layers_attribute',
            name='type_of_animal',
            field=models.CharField(blank=True, choices=[('Troglobites', 'Troglobites'), ('Troglophiles', 'Troglophiles'), ('Accidentals ', 'Accidentals '), ('Infrared eyesight ', 'Infrared eyesight '), ('Giant centipedes ', 'Giant centipedes '), ('elephantnose fish', 'elephantnose fish')], max_length=100, null=True),
        ),
    ]
